- hosts: all
  tasks:
    - name: Install packages
      become: true
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - curl
        - git-core
    - name: Install golang binary
      become: true
      get_url:
        url: https://dl.google.com/go/go1.10.3.linux-amd64.tar.gz
        dest: /usr/local/src/golang.tar.gz
    - name: Unzip golang binary
      become: true
      unarchive:
        src: /usr/local/src/golang.tar.gz
        dest: /usr/local/
        remote_src: yes
    - name: Export goroot
      lineinfile:
        path: ~/.profile
        line: export GOROOT=/usr/local/go
    - name: Export gopath
      lineinfile:
        path: ~/.profile
        line: export GOPATH=$HOME/go
    - name: set path
      lineinfile:
        path: ~/.profile
        line: export PATH=$PATH:$GOPATH/bin:$GOROOT/bin
    - name: Reload bash
      command: bash -lc "source ~/.profile"
    - name: Install delve
      command: bash -lc "go get -u github.com/derekparker/delve/cmd/dlv"
