- hosts: all
  tasks:
    - name: Install curl
      become: true
      apt:
        name: curl
    - name: Install golang binary
      become: true
      get_url:
        url: https://dl.google.com/go/go1.10.3.linux-amd64.tar.gz
        dest: /usr/local/src/golang.tar.gz
    - name: Unzip golang binary
      become: true
      unarchive:
        src: /usr/local/src/golang.tar.gz
        dest: /usr/local/
        remote_src: yes
    - name: Export goroot
      lineinfile:
        path: ~/.profile
        line: export GOROOT=/usr/local/go
    - name: Export gopath
      lineinfile:
        path: ~/.profile
        line: export PATH=$PATH:$GOROOT/bin
    - name: Reload bash
      command: bash -lc "source ~/.profile"
